
- name: Install Bacula on Debian
  include_tasks: 01-install-debian.yml
  when: "ansible_distribution == 'Debian'"

- name: Get the db password
  shell: >
    /usr/bin/grep ^dbc_dbpass /etc/dbconfig-common/bacula-director-* | /usr/bin/sed "s/'$//;s/.*'//"
  register: bacula_db_pass

- name: Update backular-dir config
  lineinfile:
    path: "/etc/bacula/bacula-dir.conf"
    regexp: '.*dbname.*=.*".*";.*dbuser.*=.*".*";.*dbpassword.*=.*".*"'
    line: '  dbname = "bacula"; dbuser = "bacula"; dbpassword = "{{ bacula_db_pass.stdout }}"'

- name: Start bacular-dir
  systemd:
    name: "bacula-director"
    state: started
    enabled: yes

- name: Upload sudoers config file
  template:
    src: etc/sudoers.d/bacula-web-ctrl
    dest: /etc/sudoers.d/bacula-web-ctrl
    owner: root
    group: root
    mode: '0644'
